### ISSUE TITLE
Issue when trying to apply weather

### ISSUE THREAD

**Issue by roi007leaf** [paulo-roger/weatherfx#1]
Not sure what causes this but from short debugging it seems to be related to the flag of the current weather not being set so it's null
and then throws the error here 
![image](https://user-images.githubusercontent.com/17231451/191415097-ebe84962-bd1e-460e-b2d1-2825572a7b08.png)

**Comment by roi007leaf** [comment]
Found the issue, if anyone has this issue know that this option under Weather Control module settings must be turned on (Perhaps it's best to make sure that this setting is turned on before running the weatherTrigger function and throw an error so the user will know what's wrong and also point it out in the README :-))
![image](https://user-images.githubusercontent.com/17231451/191415393-aadda3a6-6a5c-441f-bc2e-896c5bec223f.png)

**Comment by paulo-roger** [comment]
Good catch! I will update it. Thanks!
