### ISSUE TITLE
[Bug] Performance Issues with Heavy Rain/Thunderstorm

### ISSUE THREAD

**Issue by RinVindor** [paulo-roger/weatherfx#2]
So running a test of the weather, when it applies effects for Heavy Rain or Thunderstorms my FPS drops to about 2-3 FPS, all other effects do not cause this, and I sit at a little bit above 60+ the whole time with anything else.

Not really sure whats causing it but figured I'd mention it.

**Comment by paulo-roger** [comment]
Thanks for the feedback, in the case of Heavy Rain and Thunderstorm I have set more filters and effects than the other cases, that might impact performance a little, yeah.
As users give more feedback I can work into trying to find a setting that runs smooth for everyone.

**Comment by SirMotte** [comment]
I can confirm this. Further testing revealed, that the effects of FXMaster themselves are somewhat resource heavy, especially with high resolutions (and high resolutions scenes). It's not so much your settings but performance issues in general.

**Comment by RinVindor** [comment]
Yeah I just wanted to make sure it was known. I build custom rigs for people currently this one with the issue is a i9 11850K with 32 GB RAM, paired with a RTX 3070, everything running is stored on 2 M.2 Drives, both are Gen 4. I only tested it on one of the monitors my primary which is a 1440p 144hz monitor, but the FPS cap is obv 60 for Foundry. Not sure if this helps any.

**Comment by paulo-roger** [comment]
I am releasing an update now that address this problem, please let me know how it goes. I will leave this issue open so you can comment here.

**Comment by SirMotte** [comment]
> I am releasing an update now that address this problem, please let me know how it goes. I will leave this issue open so you can comment here.

I can confirm, that on smaller maps this has increased fps considerably. No problems at all.
On my world map however, which is a whopping 14000x12000 px large and around  170mb file size. The effects still causes massive lags that leave the ui unresponsive for a few a seconds, until the next frame is rendered, just to lock up again.

This is, very likely a problem with general performance, not necessarily with your settings, as the simple light rain effect, without anything else causes this behavior too. So a report would probably fit better in the issue tracker of the FXMaster repo. 

I would not wonder if I was declared mad to use such a map in the first place :).

My Rig:
Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz   4.01 GHz
Geforce RTX 2080
16,0 GB Ram


Thank you for this wonderful little tool, it makes things a lot easier!

**Comment by paulo-roger** [comment]
Alright! I will close this issue for now. Thank you.
