### ISSUE TITLE
Suggestion: Auto-updating only on Hour Change, not per time-change

### ISSUE THREAD

**Issue by WThunderspirit** [paulo-roger/weatherfx#3]
I notice that I have SmallTime Running with Weather FX, and Weather FX will update on each interval of SmallTime (https://github.com/unsoluble/smalltime).  This causes Weather FX to Generate A LOT of weather!  Would it be a possibility to regenerate weather only when the hour changes?

Related to that, does WeatherFX step through changes?  Such as a Light Rain may lead to Heavy, then back to light, then cloudy, then clear?  Or is it completely random?

If completely random, would day instead of hour be better for changing?

**Comment by WThunderspirit** [comment]
I reposted this in Bird's Discord - it seems its more a Weather-Control question than Weather FX

**Comment by paulo-roger** [comment]
Since this is not a Weather FX issue I am closing this thread.
