### ISSUE TITLE
Volume Control

### ISSUE THREAD

**Issue by Puxta-lab** [paulo-roger/weatherfx#4]
Is there anyway to manage the volume of the SFX, if you happen to toggle them? If not, is it possible for that to be a feature? I like the convenience of the SFX activating with everything else, but I find them to be a bit loud sometimes.

**Comment by paulo-roger** [comment]
Good idea! I will seek to implement it in the next update.

**Comment by paulo-roger** [comment]
implemented with 1.2.0
https://github.com/LeafWulf/weatherfx/releases/tag/1.2.0
