### ISSUE TITLE
[BUG] Cannot apply weather anymore

### ISSUE THREAD

**Issue by Steelskinz** [paulo-roger/weatherfx#6]
**Module Version:** v1.2.0

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
It seems when I try to apply the weather as it should be done it actually won't work. I've disabled all my module to be sure it was not having a little fight with the others.
**To Reproduce**
1. Go to Weather FX
2. Click on Apply Weather
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/93941729/193738299-d0dc4a5a-489a-4449-a63a-1cc0c74cbfe5.png)

**Browser:**
 - Local Foundry

**Foundry Version:** 10.286

**Game System:** DND5e

**Comment by roi007leaf** [comment]
@Steelskinz enable the output to chat of the weather control module

**Comment by Steelskinz** [comment]
![image](https://user-images.githubusercontent.com/93941729/193916653-69d5364c-3fa5-46a7-a917-cd2b2d8157fb.png)
It was enabled in the beginning. I've read the Read Me to be sure I wasn't forgetting something.

**Comment by paulo-roger** [comment]
Could you try to run this from chrome or firefox and tell if the issue persists? If I understood correctly you are using the electron install right?

**Comment by Steelskinz** [comment]
I tried to run it on Vivaldi and Chrome, no difference.  Yes i'm using the installation.

**Comment by paulo-roger** [comment]
Mmm is it an apple computer?

**Comment by paulo-roger** [comment]
I am trying here still cant reproduce it. I am thinking it is some sort of non compatibility with regex I am using in the message string.

**Comment by Steelskinz** [comment]
> Mmm is it an apple computer?

Nope. Windows. I even tried before to uninstall the module to actually reinstall it.  However. I tried in a new world and it seems to work well. So the problem is in my world.

**Comment by Steelskinz** [comment]
I have reset by default the settings and it worked again. Maybe a little update bug, it happen.
